name: Publish to PyPI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ./.python-version
      - name: Install Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - name: Add Poetry to path
        run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
      - name: Run tests
        run: poetry install
      - name: Install venv
        run: poetry install  
      - name: Publish package
        run: poetry publish --build -r pypi -u __token__ -p ${{ secrets.PYPI_API_KEY }}
