name: Publish to PyPI
on:
  push:
    tags:
      - v*.*.*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read python version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.python-version
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ steps.package.outputs.content }}
      - name: Install Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - name: Add Poetry to path
        run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
      - name: Install venv
        run: poetry install
      - name: Run tests
        run: poetry run pytest
      - name: Run linter
        run: poetry run flake8
      - name: Publish package
        run: poetry publish --build -u __token__ -p ${{ secrets.PYPI_API_KEY }}
